import { InventoryItemTypes } from '../../../components/character-sheet/partials/character-inventory/enums/inventory-item-types';

export const ITEM_TYPE_LABELS: Record<InventoryItemTypes, string> = {
  [InventoryItemTypes.ARTIFACT]: 'Artifact',
  [InventoryItemTypes.HAMMER]: 'Hammer',
  [InventoryItemTypes.BOW]: 'Bow',
  [InventoryItemTypes.GUN]: 'Gun',
  [InventoryItemTypes.FAN]: 'Fan',
  [InventoryItemTypes.MACE]: 'Mace',
  [InventoryItemTypes.SCRATCH_AWL]: 'Scratch Awl',
  [InventoryItemTypes.STAVE]: 'Stave',
  [InventoryItemTypes.BODY]: 'Body',
  [InventoryItemTypes.SHIELD]: 'Shield',
  [InventoryItemTypes.LEGGINGS]: 'Leggings',
  [InventoryItemTypes.FEET]: 'Feet',
  [InventoryItemTypes.SLEEVES]: 'Sleeves',
  [InventoryItemTypes.HELMET]: 'Helmet',
  [InventoryItemTypes.GLOVES]: 'Gloves',
  [InventoryItemTypes.WAND]: 'Wand',
  [InventoryItemTypes.CENSOR]: 'Censer',
  [InventoryItemTypes.CENSER]: 'Censer',
  [InventoryItemTypes.CLAW]: 'Claw',
  [InventoryItemTypes.SWORD]: 'Sword',
  [InventoryItemTypes.RING]: 'Ring',
  [InventoryItemTypes.DAGGER]: 'Dagger',
  [InventoryItemTypes.SPELL_HEALING]: 'Healing Spell',
  [InventoryItemTypes.SPELL_DAMAGE]: 'Damage Spell',
  [InventoryItemTypes.RING_ONE]: 'Ring One',
  [InventoryItemTypes.RING_TWO]: 'Ring Two',
  [InventoryItemTypes.SPELL_ONE]: 'Spell One',
  [InventoryItemTypes.SPELL_TWO]: 'Spell Two',
  [InventoryItemTypes.TRINKET]: 'Trinket',
  [InventoryItemTypes.QUEST]: 'Quest',
};
