export enum InventoryItemTypes {
  ARTIFACT = 'artifact',
  HAMMER = 'hammer',
  BOW = 'bow',
  GUN = 'gun',
  FAN = 'fan',
  MACE = 'mace',
  SCRATCH_AWL = 'scratch-awl',
  STAVE = 'stave',
  BODY = 'body',
  SHIELD = 'shield',
  LEGGINGS = 'leggings',
  FEET = 'feet',
  SLEEVES = 'sleeves',
  HELMET = 'helmet',
  GLOVES = 'gloves',
  WAND = 'wand',
  CENSOR = 'censor',
  CENSER = 'censer',
  CLAW = 'claw',
  SWORD = 'sword',
  RING = 'ring',
  DAGGER = 'dagger',
  SPELL_HEALING = 'spell-healing',
  SPELL_DAMAGE = 'spell-damage',
  RING_ONE = 'ring-one',
  RING_TWO = 'ring-two',
  SPELL_ONE = 'spell-one',
  SPELL_TWO = 'spell-two',
  TRINKET = 'trinket',
  QUEST = 'quest',
}

export const armourPositions = [
  InventoryItemTypes.BODY,
  InventoryItemTypes.FEET,
  InventoryItemTypes.HELMET,
  InventoryItemTypes.GLOVES,
  InventoryItemTypes.LEGGINGS,
  InventoryItemTypes.SLEEVES,
];

export const weaponTypes: InventoryItemTypes[] = [
  InventoryItemTypes.STAVE,
  InventoryItemTypes.BOW,
  InventoryItemTypes.DAGGER,
  InventoryItemTypes.SCRATCH_AWL,
  InventoryItemTypes.MACE,
  InventoryItemTypes.HAMMER,
  InventoryItemTypes.GUN,
  InventoryItemTypes.FAN,
  InventoryItemTypes.WAND,
  InventoryItemTypes.CENSER,
  InventoryItemTypes.CLAW,
  InventoryItemTypes.SWORD,
  InventoryItemTypes.SHIELD,
];

export const nonArmourEquippableItems: InventoryItemTypes[] = [
  ...weaponTypes,
  InventoryItemTypes.RING,
  InventoryItemTypes.SPELL_DAMAGE,
  InventoryItemTypes.SPELL_HEALING,
  InventoryItemTypes.CENSOR,
  InventoryItemTypes.TRINKET,
  InventoryItemTypes.ARTIFACT,
];
