<?php

use Illuminate\Database\Seeder;
use App\Flare\Models\Item;

class CreateItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Item::insert([
            [
                'name'                  => 'Rusty bloody broken dagger',
                'type'                  => 'weapon',
                'base_damage'           => 3,
                'cost'                  => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Chapped, scared and ripped leather breast plate',
                'type'                 => 'body',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Steel rimmed wooden shield',
                'type'                 => 'shield',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Worn out musty old shoes',
                'type'                 => 'feet',
                'base_damage'          => null,
                'cost'                 => 10,
                'name'                 => 'Steel rimmed wooden shield',
                'type'                 => 'shield',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Torn, ripped and bloody leggings',
                'type'                 => 'leggings',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Old cotton sleeves',
                'type'                 => 'sleeves',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Ruined and burnt wooden mask',
                'type'                 => 'helmet',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Fingerless ripped gloves',
                'type'                 => 'gloves',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Quick cast rapid damage spell',
                'type'                 => 'spell',
                'base_damage'          => 5,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Quick cast rapid healing spell',
                'type'                 => 'spell',
                'base_damage'          => null,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Basic ring of hatred and despair',
                'type'                 => 'ring',
                'base_damage'          => 3,
                'cost'                 => 10,
                'base_damage_mod'      => null,
                'description'          => null,
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Virgins Petrified Blood',
                'type'                 => 'artifact',
                'base_damage'          => 25,
                'cost'                 => 1000,
                'base_damage_mod'      => '0.01',
                'description'          => 'Blood from a virgin thats been petrified.',
                'base_healing_mod'     => '0.01',
                'str_mod'              => '0.01',
                'dur_mod'              => '0.05',
                'dex_mod'              => '0.01',
                'chr_mod'              => '0.01',
                'int_mod'              => '0.01',
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Tears of a demon',
                'type'                 => 'artifact',
                'base_damage'          => 25,
                'cost'                 => 1000,
                'base_damage_mod'      => '0.01',
                'description'          => 'A tear from a demon is a rare thing indeed.',
                'base_healing_mod'     => '0.08',
                'str_mod'              => '0.01',
                'dur_mod'              => '0.01',
                'dex_mod'              => '0.01',
                'chr_mod'              => '0.05',
                'int_mod'              => '0.01',
                'ac_mod'               => '0.01',
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Conjuration Bag',
                'type'                 => 'artifact',
                'base_damage'          => 25,
                'cost'                 => 1000,
                'base_damage_mod'      => '0.01',
                'description'          => 'A witch doctors conjuration bag.',
                'base_healing_mod'     => '0.01',
                'str_mod'              => '0.01',
                'dur_mod'              => '0.01',
                'dex_mod'              => '0.01',
                'chr_mod'              => '0.01',
                'int_mod'              => '0.05',
                'ac_mod'               => '0.01',
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Ancient Soldiers Broken Sword',
                'type'                 => 'artifact',
                'base_damage'          => 25,
                'cost'                 => 1000,
                'base_damage_mod'      => '0.01',
                'description'          => 'The hilt of a long sword once used by a mighty warrior.',
                'base_healing_mod'     => '0.01',
                'str_mod'              => '0.05',
                'dur_mod'              => '0.01',
                'dex_mod'              => '0.01',
                'chr_mod'              => '0.01',
                'int_mod'              => '0.01',
                'ac_mod'               => '0.02',
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Dioxes Bow',
                'type'                 => 'artifact',
                'base_damage'          => 25,
                'cost'                 => 1000,
                'base_damage_mod'      => '0.02',
                'description'          => 'A legendary rangers quiver.',
                'base_healing_mod'     => '0.01',
                'str_mod'              => '0.01',
                'dur_mod'              => '0.01',
                'dex_mod'              => '0.05',
                'chr_mod'              => '0.01',
                'int_mod'              => '0.01',
                'ac_mod'               => '0.01',
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
            [
                'name'                 => 'Flask of Fresh Air',
                'type'                 => 'quest',
                'base_damage'          => null,
                'cost'                 => null,
                'base_damage_mod'      => null,
                'description'          => 'Allows you to walk on water.',
                'base_healing_mod'     => null,
                'str_mod'              => null,
                'dur_mod'              => null,
                'dex_mod'              => null,
                'chr_mod'              => null,
                'int_mod'              => null,
                'ac_mod'               => null,
                'skill_name'           => null,
                'skill_training_bonus' => null,
            ],
        ]);
    }
}
