export default interface ItemAffixDefinition {
  id: number;
  name: string;
  description: string;
  base_damage_mod: number | string | null;
  base_healing_mod: number | string | null;
  base_ac_mod: number | string | null;
  str_mod: number | null;
  dur_mod: number | null;
  dex_mod: number | null;
  chr_mod: number | null;
  int_mod: number | null;
  int_required: number;
  skill_level_required: number;
  skill_level_trivial: number;
  skill_name: string | null;
  skill_bonus: number | null;
  skill_training_bonus: number | null;
  cost: number;
  type: 'prefix' | 'suffix';
  created_at: string;
  updated_at: string;
  can_drop: boolean;
  agi_mod: number;
  focus_mod: number;
  affects_skill_type: string | null;
  damage_can_stack: boolean;
  irresistible_damage: boolean;
  str_reduction: number;
  dur_reduction: number;
  dex_reduction: number;
  chr_reduction: number;
  int_reduction: number;
  agi_reduction: number;
  focus_reduction: number;
  steal_life_amount: number | null;
  entranced_chance: number;
  reduces_enemy_stats: number;
  devouring_light: number;
  skill_reduction: number;
  resistance_reduction: number;
  randomly_generated: boolean;
  affix_type: number;
  damage_amount: number | null;
}
