import ItemFormDefinition from '../api/definitions/item-form-definition';
import ItemFormStateDefinition from '../definitions/item-form-state-definition';

const toStringValue = (value: number | null): string =>
  value === null ? '' : String(value);

export const createItemFormState = (
  item: ItemFormDefinition | null
): ItemFormStateDefinition => {
  if (!item) {
    return {
      name: '',
      type: '',
      description: '',
      default_position: '',
      market_sellable: true,
      can_drop: true,
      cost: '',
      gold_dust_cost: '',
      shards_cost: '',
      copper_coin_cost: '',
      gold_bars_cost: '',
      alchemy_type: '',
      specialty_type: '',
      base_damage: '',
      base_ac: '',
      base_healing: '',
      base_damage_mod: '',
      base_ac_mod: '',
      base_healing_mod: '',
      str_mod: '',
      dur_mod: '',
      dex_mod: '',
      chr_mod: '',
      int_mod: '',
      agi_mod: '',
      focus_mod: '',
      ambush_chance: '',
      ambush_resistance: '',
      counter_chance: '',
      counter_resistance: '',
      effect: '',
      drop_location_id: null,
      unlocks_class_id: null,
      item_skill_id: null,
      skill_name: '',
      skill_bonus: '',
      skill_training_bonus: '',
      fight_time_out_mod_bonus: '',
      move_time_out_mod_bonus: '',
      xp_bonus: '',
      ignores_caps: false,
      can_resurrect: false,
      resurrection_chance: '',
      spell_evasion: '',
      artifact_annulment: '',
      healing_reduction: '',
      affix_damage_reduction: '',
      devouring_light: '',
      devouring_darkness: '',
      can_craft: false,
      craft_only: false,
      crafting_type: '',
      skill_level_required: '',
      skill_level_trivial: '',
      usable: false,
      can_stack: false,
      lasts_for: '',
      stat_increase: false,
      increase_stat_by: '',
      damages_kingdoms: false,
      kingdom_damage: '',
      affects_skill_type: null,
      increase_skill_bonus_by: '',
      increase_skill_training_bonus_by: '',
      can_use_on_other_items: false,
      holy_level: '',
      gains_additional_level: false,
    };
  }

  return {
    name: item.name,
    type: item.type,
    description: item.description,
    default_position: item.default_position ?? '',
    market_sellable: item.market_sellable,
    can_drop: item.can_drop,
    cost: toStringValue(item.cost),
    gold_dust_cost: toStringValue(item.gold_dust_cost),
    shards_cost: toStringValue(item.shards_cost),
    copper_coin_cost: toStringValue(item.copper_coin_cost),
    gold_bars_cost: toStringValue(item.gold_bars_cost),
    alchemy_type: item.alchemy_type ?? '',
    specialty_type: item.specialty_type ?? '',
    base_damage: toStringValue(item.base_damage),
    base_ac: toStringValue(item.base_ac),
    base_healing: toStringValue(item.base_healing),
    base_damage_mod: toStringValue(item.base_damage_mod),
    base_ac_mod: toStringValue(item.base_ac_mod),
    base_healing_mod: toStringValue(item.base_healing_mod),
    str_mod: toStringValue(item.str_mod),
    dur_mod: toStringValue(item.dur_mod),
    dex_mod: toStringValue(item.dex_mod),
    chr_mod: toStringValue(item.chr_mod),
    int_mod: toStringValue(item.int_mod),
    agi_mod: toStringValue(item.agi_mod),
    focus_mod: toStringValue(item.focus_mod),
    ambush_chance: toStringValue(item.ambush_chance),
    ambush_resistance: toStringValue(item.ambush_resistance),
    counter_chance: toStringValue(item.counter_chance),
    counter_resistance: toStringValue(item.counter_resistance),
    effect: item.effect ?? '',
    drop_location_id: item.drop_location_id,
    unlocks_class_id: item.unlocks_class_id,
    item_skill_id: item.item_skill_id,
    skill_name: item.skill_name ?? '',
    skill_bonus: toStringValue(item.skill_bonus),
    skill_training_bonus: toStringValue(item.skill_training_bonus),
    fight_time_out_mod_bonus: toStringValue(item.fight_time_out_mod_bonus),
    move_time_out_mod_bonus: toStringValue(item.move_time_out_mod_bonus),
    xp_bonus: toStringValue(item.xp_bonus),
    ignores_caps: item.ignores_caps,
    can_resurrect: item.can_resurrect,
    resurrection_chance: toStringValue(item.resurrection_chance),
    spell_evasion: toStringValue(item.spell_evasion),
    artifact_annulment: toStringValue(item.artifact_annulment),
    healing_reduction: toStringValue(item.healing_reduction),
    affix_damage_reduction: toStringValue(item.affix_damage_reduction),
    devouring_light: toStringValue(item.devouring_light),
    devouring_darkness: toStringValue(item.devouring_darkness),
    can_craft: item.can_craft,
    craft_only: item.craft_only,
    crafting_type: item.crafting_type ?? '',
    skill_level_required: toStringValue(item.skill_level_required),
    skill_level_trivial: toStringValue(item.skill_level_trivial),
    usable: item.usable,
    can_stack: item.can_stack,
    lasts_for: toStringValue(item.lasts_for),
    stat_increase: item.stat_increase,
    increase_stat_by: toStringValue(item.increase_stat_by),
    damages_kingdoms: item.damages_kingdoms,
    kingdom_damage: toStringValue(item.kingdom_damage),
    affects_skill_type: item.affects_skill_type,
    increase_skill_bonus_by: toStringValue(item.increase_skill_bonus_by),
    increase_skill_training_bonus_by: toStringValue(
      item.increase_skill_training_bonus_by
    ),
    can_use_on_other_items: item.can_use_on_other_items,
    holy_level: toStringValue(item.holy_level),
    gains_additional_level: item.gains_additional_level,
  };
};
