import { SidePeekComponentRegistrationEnum } from './side-peek-component-registration-enum';
import GameMapCoordinateSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-coordinate-side-peek-props';
import GameMapFormSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-form-side-peek-props';
import GameMapImportSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-import-side-peek-props';
import GameMapKingdomSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-kingdom-side-peek-props';
import GameMapLocationSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-location-side-peek-props';
import GameMapNpcSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-npc-side-peek-props';
import AdminItemDetailSidePeekProps from '../../../../../admin/items/components/side-peeks/types/admin-item-detail-side-peek-props';
import ItemFormSidePeekProps from '../../../../../admin/items/components/side-peeks/types/item-form-side-peek-props';
import ItemImportSidePeekProps from '../../../../../admin/items/components/side-peeks/types/item-import-side-peek-props';
import LocationFormSidePeekProps from '../../../../../admin/locations/components/side-peeks/types/location-form-side-peek-props';
import LocationImportSidePeekProps from '../../../../../admin/locations/components/side-peeks/types/location-import-side-peek-props';
import NpcFormSidePeekProps from '../../../../../admin/npcs/components/side-peeks/types/npc-form-side-peek-props';
import NpcImportSidePeekProps from '../../../../../admin/npcs/components/side-peeks/types/npc-import-side-peek-props';
import BugReportSidePeekProps from '../../../../../admin/monitoring/logs-dashboard/components/side-peeks/types/bug-report-side-peek-props';
import LogEntrySidePeekProps from '../../../../../admin/monitoring/logs-dashboard/components/side-peeks/types/log-entry-side-peek-props';
import BackpackProps from '../../character-inventory/backpack/types/backpack-props';
import GemBagProps from '../../character-inventory/gem-bag/types/gem-bag-props';
import SetsProps from '../../character-inventory/sets/types/sets-props';
import UsableItemsProps from '../../character-inventory/usable-items/types/usable-items-props';
import CraftedItemProps from '../../crafted-item/types/crafted-item-props';
import ItemDetailsProps from '../../item-details/types/item-details-props';
import ConjureProps from '../../map-actions/conjure/types/conjure-props';
import CharacterKingdomDetailsProps from '../../map-actions/kingdom-details/types/character-kingdom-details-props';
import LocationDetailsProps from '../../map-actions/location-details/types/location-details-props';
import SetSailProps from '../../map-actions/set-sail/types/set-sail-props';
import TeleportProps from '../../map-actions/teleport/types/teleport-props';
import TraversePropsDefinition from '../../map-actions/traverse/definitions/traverse-props-definition';
import ServerChatItemProps from '../../server-chat-item/types/server-chat-item-props';

export type SidePeekComponentPropsMap = {
  [SidePeekComponentRegistrationEnum.BACKPACK]: BackpackProps;
  [SidePeekComponentRegistrationEnum.GEM_BAG]: GemBagProps;
  [SidePeekComponentRegistrationEnum.USABLE_ITEMS]: UsableItemsProps;
  [SidePeekComponentRegistrationEnum.SETS]: SetsProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_TELEPORT]: TeleportProps;
  [SidePeekComponentRegistrationEnum.LOCATION_DETAILS]: LocationDetailsProps;
  [SidePeekComponentRegistrationEnum.CHARACTER_KINGDOM_DETAILS]: CharacterKingdomDetailsProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_TRAVERSE]: TraversePropsDefinition;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_SET_SAIL]: SetSailProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_CONJURE]: ConjureProps;
  [SidePeekComponentRegistrationEnum.SERVER_CHAT_ITEM]: ServerChatItemProps;
  [SidePeekComponentRegistrationEnum.CRAFTED_ITEM]: CraftedItemProps;
  [SidePeekComponentRegistrationEnum.ITEM_DETAILS]: ItemDetailsProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOG_ENTRY]: LogEntrySidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_BUG_REPORT]: BugReportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_COORDINATE]: GameMapCoordinateSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_LOCATION]: GameMapLocationSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_NPC]: GameMapNpcSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_KINGDOM]: GameMapKingdomSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_FORM]: GameMapFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_IMPORT]: GameMapImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOCATION_FORM]: LocationFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOCATION_IMPORT]: LocationImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_NPC_FORM]: NpcFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_NPC_IMPORT]: NpcImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_DETAIL]: AdminItemDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_FORM]: ItemFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_IMPORT]: ItemImportSidePeekProps;
  // Future components go here
};
