export enum SidePeekComponentRegistrationEnum {
  /**
   * Character Inventory
   */
  BACKPACK = 'BACKPACK',
  GEM_BAG = 'GEM_BAG',
  USABLE_ITEMS = 'USABLE_ITEMS',
  SETS = 'SETS',

  /**
   * Map Actions
   */
  MAP_ACTIONS_TELEPORT = 'MAP_ACTIONS_TELEPORT',
  MAP_ACTIONS_TRAVERSE = 'MAP_ACTIONS_TRAVERSE',
  MAP_ACTIONS_SET_SAIL = 'MAP_ACTIONS_SET_SAIL',
  MAP_ACTIONS_CONJURE = 'MAP_ACTIONS_CONJURE',

  /**
   * Map Details
   */
  LOCATION_DETAILS = 'LOCATION_DETAILS',
  CHARACTER_KINGDOM_DETAILS = 'CHARACTER_KINGDOM_DETAILS',
  PLAYER_GAME_MAP_DETAIL = 'PLAYER_GAME_MAP_DETAIL',
  PLAYER_NPC_DETAIL = 'PLAYER_NPC_DETAIL',

  /**
   * Server Chat Items
   */
  SERVER_CHAT_ITEM = 'SERVER_CHAT_ITEM',

  /**
   * Crafting
   */
  CRAFTED_ITEM = 'CRAFTED_ITEM',

  /**
   * Item Details
   */
  ITEM_DETAILS = 'ITEM_DETAILS',

  /**
   * Class / Class Mastery Details
   */
  CLASS_DETAIL = 'CLASS_DETAIL',
  CLASS_MASTERY_DETAIL = 'CLASS_MASTERY_DETAIL',
  CHARACTER_CLASS_RANK_DETAIL = 'CHARACTER_CLASS_RANK_DETAIL',
  CHARACTER_CLASS_SPECIALTY_DETAIL = 'CHARACTER_CLASS_SPECIALTY_DETAIL',

  /**
   * Admin Monitoring
   */
  ADMIN_LOG_ENTRY = 'ADMIN_LOG_ENTRY',
  ADMIN_BUG_REPORT = 'ADMIN_BUG_REPORT',

  /**
   * Admin Game Maps
   */
  ADMIN_GAME_MAP_COORDINATE = 'ADMIN_GAME_MAP_COORDINATE',
  ADMIN_GAME_MAP_LOCATION = 'ADMIN_GAME_MAP_LOCATION',
  ADMIN_GAME_MAP_NPC = 'ADMIN_GAME_MAP_NPC',
  ADMIN_GAME_MAP_KINGDOM = 'ADMIN_GAME_MAP_KINGDOM',
  ADMIN_GAME_MAP_FORM = 'ADMIN_GAME_MAP_FORM',
  ADMIN_GAME_MAP_IMPORT = 'ADMIN_GAME_MAP_IMPORT',
  ADMIN_GAME_MAP_DETAIL = 'ADMIN_GAME_MAP_DETAIL',
  ADMIN_GAME_MAP_RELATED_LOCATIONS = 'ADMIN_GAME_MAP_RELATED_LOCATIONS',
  ADMIN_GAME_MAP_RELATED_NPCS = 'ADMIN_GAME_MAP_RELATED_NPCS',
  ADMIN_GAME_MAP_RELATED_MONSTERS = 'ADMIN_GAME_MAP_RELATED_MONSTERS',
  ADMIN_GAME_MAP_RELATED_QUESTS = 'ADMIN_GAME_MAP_RELATED_QUESTS',
  ADMIN_GAME_MAP_RELATED_QUEST_ITEMS = 'ADMIN_GAME_MAP_RELATED_QUEST_ITEMS',

  /**
   * Admin Locations
   */
  ADMIN_LOCATION_FORM = 'ADMIN_LOCATION_FORM',
  ADMIN_LOCATION_IMPORT = 'ADMIN_LOCATION_IMPORT',
  ADMIN_LOCATION_DETAIL = 'ADMIN_LOCATION_DETAIL',

  /**
   * Admin Npcs
   */
  ADMIN_NPC_FORM = 'ADMIN_NPC_FORM',
  ADMIN_NPC_IMPORT = 'ADMIN_NPC_IMPORT',
  ADMIN_NPC_DETAIL = 'ADMIN_NPC_DETAIL',

  /**
   * Admin Items
   */
  ADMIN_ITEM_DETAIL = 'ADMIN_ITEM_DETAIL',
  ADMIN_ITEM_FORM = 'ADMIN_ITEM_FORM',
  ADMIN_ITEM_IMPORT = 'ADMIN_ITEM_IMPORT',

  /**
   * Admin Quests
   */
  ADMIN_QUEST_DETAIL = 'ADMIN_QUEST_DETAIL',

  /**
   * Admin Monsters
   */
  ADMIN_MONSTER_DETAIL = 'ADMIN_MONSTER_DETAIL',

  /**
   * Admin Classes
   */
  ADMIN_CLASS_IMPORT = 'ADMIN_CLASS_IMPORT',

  /**
   * Admin Races
   */
  ADMIN_RACE_IMPORT = 'ADMIN_RACE_IMPORT',

  /**
   * Admin Class Masteries
   */
  ADMIN_CLASS_MASTERY_IMPORT = 'ADMIN_CLASS_MASTERY_IMPORT',

  /**
   * Admin Map Gems
   */
  ADMIN_MAP_GEM_IMPORT = 'ADMIN_MAP_GEM_IMPORT',
  ADMIN_MAP_GEM_DETAIL = 'ADMIN_MAP_GEM_DETAIL',
  ADMIN_MAP_GEM_BULK_ROLL_RESULT = 'ADMIN_MAP_GEM_BULK_ROLL_RESULT',

  /**
   * Admin Location Gems
   */
  ADMIN_LOCATION_GEM_IMPORT = 'ADMIN_LOCATION_GEM_IMPORT',
  ADMIN_LOCATION_GEM_DETAIL = 'ADMIN_LOCATION_GEM_DETAIL',
  ADMIN_LOCATION_GEM_BULK_ROLL_RESULT = 'ADMIN_LOCATION_GEM_BULK_ROLL_RESULT',
}
