export enum SidePeekComponentRegistrationEnum {
  /**
   * Character Inventory
   */
  BACKPACK = 'BACKPACK',
  GEM_BAG = 'GEM_BAG',
  USABLE_ITEMS = 'USABLE_ITEMS',
  SETS = 'SETS',

  /**
   * Map Actions
   */
  MAP_ACTIONS_TELEPORT = 'MAP_ACTIONS_TELEPORT',
  MAP_ACTIONS_TRAVERSE = 'MAP_ACTIONS_TRAVERSE',
  MAP_ACTIONS_SET_SAIL = 'MAP_ACTIONS_SET_SAIL',
  MAP_ACTIONS_CONJURE = 'MAP_ACTIONS_CONJURE',

  /**
   * Map Details
   */
  LOCATION_DETAILS = 'LOCATION_DETAILS',
  CHARACTER_KINGDOM_DETAILS = 'CHARACTER_KINGDOM_DETAILS',

  /**
   * Server Chat Items
   */
  SERVER_CHAT_ITEM = 'SERVER_CHAT_ITEM',

  /**
   * Crafting
   */
  CRAFTED_ITEM = 'CRAFTED_ITEM',

  /**
   * Item Details
   */
  ITEM_DETAILS = 'ITEM_DETAILS',

  /**
   * Admin Monitoring
   */
  ADMIN_LOG_ENTRY = 'ADMIN_LOG_ENTRY',
  ADMIN_BUG_REPORT = 'ADMIN_BUG_REPORT',

  /**
   * Admin Game Maps
   */
  ADMIN_GAME_MAP_COORDINATE = 'ADMIN_GAME_MAP_COORDINATE',
  ADMIN_GAME_MAP_LOCATION = 'ADMIN_GAME_MAP_LOCATION',
  ADMIN_GAME_MAP_NPC = 'ADMIN_GAME_MAP_NPC',
  ADMIN_GAME_MAP_KINGDOM = 'ADMIN_GAME_MAP_KINGDOM',
  ADMIN_GAME_MAP_FORM = 'ADMIN_GAME_MAP_FORM',
  ADMIN_GAME_MAP_IMPORT = 'ADMIN_GAME_MAP_IMPORT',
}
