import {
  SidePeekComponentRegistrationEnum,
  SidePeekComponentRegistrationEnum as Registration,
} from './side-peek-component-registration-enum';
import ClassMasteryImportSidePeekProps from '../../../../../admin/class-masteries/components/side-peeks/types/class-mastery-import-side-peek-props';
import ClassImportSidePeekProps from '../../../../../admin/classes/components/side-peeks/types/class-import-side-peek-props';
import AdminGameMapDetailSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/admin-game-map-detail-side-peek-props';
import GameMapCoordinateSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-coordinate-side-peek-props';
import GameMapFormSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-form-side-peek-props';
import GameMapImportSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-import-side-peek-props';
import GameMapKingdomSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-kingdom-side-peek-props';
import GameMapLocationSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-location-side-peek-props';
import GameMapNpcSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-npc-side-peek-props';
import GameMapRelatedLocationsSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-related-locations-side-peek-props';
import GameMapRelatedMonstersSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-related-monsters-side-peek-props';
import GameMapRelatedNpcsSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-related-npcs-side-peek-props';
import GameMapRelatedQuestItemsSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-related-quest-items-side-peek-props';
import GameMapRelatedQuestsSidePeekProps from '../../../../../admin/game-maps/components/side-peeks/types/game-map-related-quests-side-peek-props';
import AdminItemDetailSidePeekProps from '../../../../../admin/items/components/side-peeks/types/admin-item-detail-side-peek-props';
import ItemExportSidePeekProps from '../../../../../admin/items/components/side-peeks/types/item-export-side-peek-props';
import ItemFormSidePeekProps from '../../../../../admin/items/components/side-peeks/types/item-form-side-peek-props';
import ItemImportSidePeekProps from '../../../../../admin/items/components/side-peeks/types/item-import-side-peek-props';
import AdminLocationGemDetailSidePeekProps from '../../../../../admin/location-gems/components/side-peeks/types/admin-location-gem-detail-side-peek-props';
import AdminLocationGemRollDetailSidePeekProps from '../../../../../admin/location-gems/components/side-peeks/types/admin-location-gem-roll-detail-side-peek-props';
import LocationGemBulkRollResultSidePeekProps from '../../../../../admin/location-gems/components/side-peeks/types/location-gem-bulk-roll-result-side-peek-props';
import LocationGemImportSidePeekProps from '../../../../../admin/location-gems/components/side-peeks/types/location-gem-import-side-peek-props';
import AdminLocationDetailSidePeekProps from '../../../../../admin/locations/components/side-peeks/types/admin-location-detail-side-peek-props';
import LocationFormSidePeekProps from '../../../../../admin/locations/components/side-peeks/types/location-form-side-peek-props';
import LocationImportSidePeekProps from '../../../../../admin/locations/components/side-peeks/types/location-import-side-peek-props';
import AdminMapGemDetailSidePeekProps from '../../../../../admin/map-gems/components/side-peeks/types/admin-map-gem-detail-side-peek-props';
import AdminMapGemRollDetailSidePeekProps from '../../../../../admin/map-gems/components/side-peeks/types/admin-map-gem-roll-detail-side-peek-props';
import MapGemBulkRollResultSidePeekProps from '../../../../../admin/map-gems/components/side-peeks/types/map-gem-bulk-roll-result-side-peek-props';
import MapGemImportSidePeekProps from '../../../../../admin/map-gems/components/side-peeks/types/map-gem-import-side-peek-props';
import BugReportSidePeekProps from '../../../../../admin/monitoring/logs-dashboard/components/side-peeks/types/bug-report-side-peek-props';
import LogEntrySidePeekProps from '../../../../../admin/monitoring/logs-dashboard/components/side-peeks/types/log-entry-side-peek-props';
import AdminMonsterDetailSidePeekProps from '../../../../../admin/monsters/components/side-peeks/types/admin-monster-detail-side-peek-props';
import AdminNpcDetailSidePeekProps from '../../../../../admin/npcs/components/side-peeks/types/admin-npc-detail-side-peek-props';
import NpcFormSidePeekProps from '../../../../../admin/npcs/components/side-peeks/types/npc-form-side-peek-props';
import NpcImportSidePeekProps from '../../../../../admin/npcs/components/side-peeks/types/npc-import-side-peek-props';
import AdminQuestDetailSidePeekProps from '../../../../../admin/quests/components/side-peeks/types/admin-quest-detail-side-peek-props';
import RaceImportSidePeekProps from '../../../../../admin/races/components/side-peeks/types/race-import-side-peek-props';
import BackpackProps from '../../character-inventory/backpack/types/backpack-props';
import GemBagProps from '../../character-inventory/gem-bag/types/gem-bag-props';
import SetsProps from '../../character-inventory/sets/types/sets-props';
import UsableItemsProps from '../../character-inventory/usable-items/types/usable-items-props';
import CraftedItemProps from '../../crafted-item/types/crafted-item-props';
import CharacterClassRankDetailSidePeekProps from '../../game-data/types/character-class-rank-detail-side-peek-props';
import CharacterClassSpecialtyDetailSidePeekProps from '../../game-data/types/character-class-specialty-detail-side-peek-props';
import ClassDetailSidePeekProps from '../../game-data/types/class-detail-side-peek-props';
import ClassMasteryDetailSidePeekProps from '../../game-data/types/class-mastery-detail-side-peek-props';
import PlayerGameMapDetailSidePeekProps from '../../game-data/types/player-game-map-detail-side-peek-props';
import PlayerNpcDetailSidePeekProps from '../../game-data/types/player-npc-detail-side-peek-props';
import ItemDetailsProps from '../../item-details/types/item-details-props';
import ConjureProps from '../../map-actions/conjure/types/conjure-props';
import GemWorldProps from '../../map-actions/gem-world/types/gem-world-props';
import CharacterKingdomDetailsProps from '../../map-actions/kingdom-details/types/character-kingdom-details-props';
import LocationDetailsProps from '../../map-actions/location-details/types/location-details-props';
import SetSailProps from '../../map-actions/set-sail/types/set-sail-props';
import TeleportProps from '../../map-actions/teleport/types/teleport-props';
import TraversePropsDefinition from '../../map-actions/traverse/definitions/traverse-props-definition';
import ServerChatItemProps from '../../server-chat-item/types/server-chat-item-props';

export type SidePeekComponentPropsMap = {
  [SidePeekComponentRegistrationEnum.BACKPACK]: BackpackProps;
  [SidePeekComponentRegistrationEnum.GEM_BAG]: GemBagProps;
  [SidePeekComponentRegistrationEnum.USABLE_ITEMS]: UsableItemsProps;
  [SidePeekComponentRegistrationEnum.SETS]: SetsProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_TELEPORT]: TeleportProps;
  [SidePeekComponentRegistrationEnum.LOCATION_DETAILS]: LocationDetailsProps;
  [SidePeekComponentRegistrationEnum.CHARACTER_KINGDOM_DETAILS]: CharacterKingdomDetailsProps;
  [SidePeekComponentRegistrationEnum.PLAYER_GAME_MAP_DETAIL]: PlayerGameMapDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.PLAYER_NPC_DETAIL]: PlayerNpcDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_TRAVERSE]: TraversePropsDefinition;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_SET_SAIL]: SetSailProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_CONJURE]: ConjureProps;
  [SidePeekComponentRegistrationEnum.MAP_ACTIONS_GEM_WORLD]: GemWorldProps;
  [SidePeekComponentRegistrationEnum.SERVER_CHAT_ITEM]: ServerChatItemProps;
  [SidePeekComponentRegistrationEnum.CRAFTED_ITEM]: CraftedItemProps;
  [SidePeekComponentRegistrationEnum.ITEM_DETAILS]: ItemDetailsProps;
  [SidePeekComponentRegistrationEnum.CLASS_DETAIL]: ClassDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.CLASS_MASTERY_DETAIL]: ClassMasteryDetailSidePeekProps;
  [Registration.CHARACTER_CLASS_RANK_DETAIL]: CharacterClassRankDetailSidePeekProps;
  [Registration.CHARACTER_CLASS_SPECIALTY_DETAIL]: CharacterClassSpecialtyDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOG_ENTRY]: LogEntrySidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_BUG_REPORT]: BugReportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_COORDINATE]: GameMapCoordinateSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_LOCATION]: GameMapLocationSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_NPC]: GameMapNpcSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_KINGDOM]: GameMapKingdomSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_FORM]: GameMapFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_IMPORT]: GameMapImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_DETAIL]: AdminGameMapDetailSidePeekProps;
  [Registration.ADMIN_GAME_MAP_RELATED_LOCATIONS]: GameMapRelatedLocationsSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_GAME_MAP_RELATED_NPCS]: GameMapRelatedNpcsSidePeekProps;
  [Registration.ADMIN_GAME_MAP_RELATED_MONSTERS]: GameMapRelatedMonstersSidePeekProps;
  [Registration.ADMIN_GAME_MAP_RELATED_QUESTS]: GameMapRelatedQuestsSidePeekProps;
  [Registration.ADMIN_GAME_MAP_RELATED_QUEST_ITEMS]: GameMapRelatedQuestItemsSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOCATION_FORM]: LocationFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOCATION_IMPORT]: LocationImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOCATION_DETAIL]: AdminLocationDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_NPC_FORM]: NpcFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_NPC_IMPORT]: NpcImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_NPC_DETAIL]: AdminNpcDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_DETAIL]: AdminItemDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_FORM]: ItemFormSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_IMPORT]: ItemImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_ITEM_EXPORT]: ItemExportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_QUEST_DETAIL]: AdminQuestDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_MONSTER_DETAIL]: AdminMonsterDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_CLASS_IMPORT]: ClassImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_RACE_IMPORT]: RaceImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_CLASS_MASTERY_IMPORT]: ClassMasteryImportSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_MAP_GEM_IMPORT]: MapGemImportSidePeekProps;
  [Registration.ADMIN_MAP_GEM_DETAIL]: AdminMapGemDetailSidePeekProps;
  [Registration.ADMIN_MAP_GEM_BULK_ROLL_RESULT]: MapGemBulkRollResultSidePeekProps;
  [Registration.ADMIN_MAP_GEM_ROLL_DETAIL]: AdminMapGemRollDetailSidePeekProps;
  [SidePeekComponentRegistrationEnum.ADMIN_LOCATION_GEM_IMPORT]: LocationGemImportSidePeekProps;
  [Registration.ADMIN_LOCATION_GEM_DETAIL]: AdminLocationGemDetailSidePeekProps;
  [Registration.ADMIN_LOCATION_GEM_BULK_ROLL_RESULT]: LocationGemBulkRollResultSidePeekProps;
  [Registration.ADMIN_LOCATION_GEM_ROLL_DETAIL]: AdminLocationGemRollDetailSidePeekProps;
  // Future components go here
};
