import InventoryCountDefinition from './inventory-count-definition';

import ElementalAtonementDefinition from 'game-data/api-data-definitions/character/elemental-atonement-definition';
import { ReincarnationInfoDefinition } from 'game-data/api-data-definitions/character/reincarnation-info-definition';
import ResistanceInfoDefinition from 'game-data/api-data-definitions/character/resistance-info-definition';

export default interface CharacterSheetDefinition {
  id: number;
  user_id: number;
  game_map_id: number;
  name: string;
  class: string;
  class_id: number;
  class_bonus_chance: number;
  race: string;
  race_id: number;
  level: number;
  max_level: number;
  xp: number;
  xp_next: number;
  to_hit_stat: string;
  ac: number;
  attack: number;
  health: number;
  resurrection_chance: number;
  gold: number;
  gold_dust: number;
  shards: number;
  copper_coins: number;
  str_raw: number;
  dex_raw: number;
  int_raw: number;
  dur_raw: number;
  agi_raw: number;
  chr_raw: number;
  focus_raw: number;
  str_modded: number;
  dex_modded: number;
  int_modded: number;
  dur_modded: number;
  agi_modded: number;
  chr_modded: number;
  focus_modded: number;
  weapon_attack: number;
  voided_weapon_attack: number;
  ring_damage: number;
  spell_damage: number;
  voided_spell_damage: number;
  healing_amount: number;
  voided_healing_amount: number;
  gold_bars: number;
  inventory_count: InventoryCountDefinition;
  resistance_info: ResistanceInfoDefinition;
  elemental_atonements: ElementalAtonementDefinition;
  reincarnation_info: ReincarnationInfoDefinition;

  is_admin?: boolean;
  is_silenced?: boolean | null;
  can_talk_again_at?: string | null;
  view_port?: number;
  is_automation_running?: boolean;
}
