export enum LocationTypes {
  PURGATORY_SMITH_HOUSE,
  GOLD_MINES,
  PURGATORY_DUNGEONS,
  UNDERWATER_CAVES,
  TEAR_FABRIC_TIME,
  THE_OLD_CHURCH,
  TWISTED_GATE,
  ALCHEMY_CHURCH,
  LORDS_STRONG_HOLD,
  BROKEN_ANVIL,
  TWSITED_MAIDENS_DUNGEONS,
  CAVE_OF_MEMORIES,
}
