<table>
    <thead>
    <tr>
        <th>id</th>
        <th>npc_id</th>
        <th>command</th>
        <th>command_type</th>
    </tr>
    </thead>
    <tbody>
    @foreach($commands as $command)
        <tr>
            <td>{{$command->id}}</td>
            <td>{{$command->npc_id}}</td>
            <td>{{$command->command}}</td>
            <td>{{$command->command_type}}</td>
        </tr>
    @endforeach
    </tbody>
</table>
