export enum CharacterGemModifierType {
  GEM_ABILITY = 'gem_ability',
  STRENGTH = 'strength',
  DEXTERITY = 'dexterity',
  INTELLIGENCE = 'intelligence',
  DURABILITY = 'durability',
  CHARISMA = 'charisma',
  AGILITY = 'agility',
  FOCUS = 'focus',
  BASE_DAMAGE_MOD = 'base_damage_mod',
  BASE_AC_MOD = 'base_ac_mod',
  BASE_HEALING_MOD = 'base_healing_mod',
  BASE_SPELL_DAMAGE_MOD = 'base_spell_damage_mod',
  CLASS_RANK_XP_GAIN = 'class_rank_xp_gain',
  CLASS_MASTERY_XP_GAIN = 'class_mastery_xp_gain',
  WEAPON_MASTERY_XP_GAIN = 'weapon_mastery_xp_gain',
  CLASS_SKILL_XP_GAIN = 'class_skill_xp_gain',
  CLASS_MASTERY_EFFECT = 'class_mastery_effect',
  WEAPON_MASTERY_EFFECT = 'weapon_mastery_effect',
  FIRE_ATONEMENT = 'fire_atonement',
  WATER_ATONEMENT = 'water_atonement',
  ICE_ATONEMENT = 'ice_atonement',
  FIRE_PENETRATION = 'fire_penetration',
  WATER_PENETRATION = 'water_penetration',
  ICE_PENETRATION = 'ice_penetration',
  GOLD_GAIN = 'gold_gain',
  GOLD_DUST_GAIN = 'gold_dust_gain',
  SHARDS_GAIN = 'shards_gain',
  COPPER_COIN_GAIN = 'copper_coin_gain',
  CHARACTER_XP_GAIN = 'character_xp_gain',
  ADDITIONAL_LEVEL_GAIN = 'additional_level_gain',
}

export const characterGemModifierLabels: Record<
  CharacterGemModifierType,
  string
> = {
  [CharacterGemModifierType.GEM_ABILITY]: 'Gem Ability',
  [CharacterGemModifierType.STRENGTH]: 'Strength',
  [CharacterGemModifierType.DEXTERITY]: 'Dexterity',
  [CharacterGemModifierType.INTELLIGENCE]: 'Intelligence',
  [CharacterGemModifierType.DURABILITY]: 'Durability',
  [CharacterGemModifierType.CHARISMA]: 'Charisma',
  [CharacterGemModifierType.AGILITY]: 'Agility',
  [CharacterGemModifierType.FOCUS]: 'Focus',
  [CharacterGemModifierType.BASE_DAMAGE_MOD]: 'Base Damage',
  [CharacterGemModifierType.BASE_AC_MOD]: 'Base AC',
  [CharacterGemModifierType.BASE_HEALING_MOD]: 'Base Healing',
  [CharacterGemModifierType.BASE_SPELL_DAMAGE_MOD]: 'Base Spell Damage',
  [CharacterGemModifierType.CLASS_RANK_XP_GAIN]: 'Class Rank XP Gain',
  [CharacterGemModifierType.CLASS_MASTERY_XP_GAIN]: 'Class Mastery XP Gain',
  [CharacterGemModifierType.WEAPON_MASTERY_XP_GAIN]: 'Weapon Mastery XP Gain',
  [CharacterGemModifierType.CLASS_SKILL_XP_GAIN]: 'Class Skill XP Gain',
  [CharacterGemModifierType.CLASS_MASTERY_EFFECT]: 'Class Mastery Effect',
  [CharacterGemModifierType.WEAPON_MASTERY_EFFECT]: 'Weapon Mastery Effect',
  [CharacterGemModifierType.FIRE_ATONEMENT]: 'Fire Atonement',
  [CharacterGemModifierType.WATER_ATONEMENT]: 'Water Atonement',
  [CharacterGemModifierType.ICE_ATONEMENT]: 'Ice Atonement',
  [CharacterGemModifierType.FIRE_PENETRATION]: 'Fire Penetration',
  [CharacterGemModifierType.WATER_PENETRATION]: 'Water Penetration',
  [CharacterGemModifierType.ICE_PENETRATION]: 'Ice Penetration',
  [CharacterGemModifierType.GOLD_GAIN]: 'Gold Gain',
  [CharacterGemModifierType.GOLD_DUST_GAIN]: 'Gold Dust Gain',
  [CharacterGemModifierType.SHARDS_GAIN]: 'Celestial Shard Gain',
  [CharacterGemModifierType.COPPER_COIN_GAIN]: 'Copper Coin Gain',
  [CharacterGemModifierType.CHARACTER_XP_GAIN]: 'Character XP Gain',
  [CharacterGemModifierType.ADDITIONAL_LEVEL_GAIN]: 'Additional Level Gain',
};

export const integerCharacterGemModifierTypes = new Set([
  CharacterGemModifierType.STRENGTH,
  CharacterGemModifierType.DEXTERITY,
  CharacterGemModifierType.INTELLIGENCE,
  CharacterGemModifierType.DURABILITY,
  CharacterGemModifierType.CHARISMA,
  CharacterGemModifierType.AGILITY,
  CharacterGemModifierType.FOCUS,
  CharacterGemModifierType.ADDITIONAL_LEVEL_GAIN,
]);
