<?php

namespace Tests\Setup;

use App\Flare\Models\Character;
use Cache;
use App\Flare\Services\BuildCharacterAttackTypes;

class AttackDataCacheSetUp {

    public function mockCacheBuilder($app) {
        $characterAttackTypes = \Mockery::mock(BuildCharacterAttackTypes::class)->makePartial();

        $app->instance(BuildCharacterAttackTypes::class, $characterAttackTypes);

        $characterAttackTypes->shouldReceive('buildCache')->withAnyArgs()->andReturn(
            $this->getCacheObject()
        );

    }

    public function mockAttackDataCache($app, Character $character) {
        $cacheDriver = app('cache')->driver();

        Cache::shouldReceive('driver')->andReturn($cacheDriver);

        Cache::shouldReceive('get')->with('character-attack-data-' . $character->id)->andReturn(
            $this->getCacheObject()
        );
    }

    public function getCacheObject(): array {
        return [
            "attack_types" => [
                "attack" => [
                    "name" => "Sample",
                    "defence" => 50,
                    "ring_damage" => 50,
                    "artifact_damage" => 50,
                    "heal_for" => 50,
                    "res_chance" => 50.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 100,
                        "non_stacking_damage" => 100,
                        "stacking_life_stealing" => 10.0,
                        "life_stealing" => 10.0,
                        "entrancing_chance" => 10.0,
                    ],
                    "weapon_damage" => 100,
                ],
                "voided_attack" => [
                    "name" => "Sample",
                    "defence" => 10,
                    "ring_damage" => 0,
                    "artifact_damage" => 0,
                    "heal_for" => 0,
                    "res_chance" => 0.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 0,
                        "non_stacking_damage" => 0,
                        "stacking_life_stealing" => 0,
                        "life_stealing" => 0,
                        "entrancing_chance" => 0,
                    ],
                    "weapon_damage" => 0,
                ],
                "cast" => [
                    "name" => "Sample",
                    "defence" => 50,
                    "ring_damage" => 50,
                    "artifact_damage" => 50,
                    "heal_for" => 50,
                    "res_chance" => 50.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 100,
                        "non_stacking_damage" => 100,
                        "stacking_life_stealing" => 10.0,
                        "life_stealing" => 10.0,
                        "entrancing_chance" => 10.0,
                    ],
                    "spell_damage" => 100,
                ],
                "voided_cast" => [
                    "name" => "Sample",
                    "defence" => 10,
                    "ring_damage" => 0,
                    "artifact_damage" => 0,
                    "heal_for" => 0,
                    "res_chance" => 0.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 0,
                        "non_stacking_damage" => 0,
                        "stacking_life_stealing" => 0,
                        "life_stealing" => 0,
                        "entrancing_chance" => 0,
                    ],
                    "spell_damage" => 0,
                ],
                "cast_and_attack" => [
                    "name" => "Sample",
                    "defence" => 50,
                    "ring_damage" => 50,
                    "artifact_damage" => 50,
                    "heal_for" => 50,
                    "res_chance" => 50.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 100,
                        "non_stacking_damage" => 100,
                        "stacking_life_stealing" => 10.0,
                        "life_stealing" => 10.0,
                        "entrancing_chance" => 10.0,
                    ],
                    "spell_damage" => 100,
                    "weapon_damage" => 100.0,
                ],
                "voided_cast_and_attack" => [
                    "name" => "Sample",
                    "defence" => 10,
                    "ring_damage" => 0,
                    "artifact_damage" => 0,
                    "heal_for" => 0,
                    "res_chance" => 0.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 0,
                        "non_stacking_damage" => 0,
                        "stacking_life_stealing" => 0,
                        "life_stealing" => 0,
                        "entrancing_chance" => 0,
                    ],
                    "spell_damage" => 0,
                    "weapon_damage" => 0,
                ],
                "attack_and_cast" => [
                    "name" => "Sample",
                    "defence" => 50,
                    "ring_damage" => 50,
                    "artifact_damage" => 50,
                    "heal_for" => 50,
                    "res_chance" => 50.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 100,
                        "non_stacking_damage" => 100,
                        "stacking_life_stealing" => 10.0,
                        "life_stealing" => 10.0,
                        "entrancing_chance" => 10.0,
                    ],
                    "spell_damage" => 100,
                    "weapon_damage" => 146.0,
                ],
                "voided_attack_and_cast" => [
                    "name" => "Sample",
                    "defence" => 10,
                    "ring_damage" => 0,
                    "artifact_damage" => 0,
                    "heal_for" => 0,
                    "res_chance" => 0.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 0,
                        "non_stacking_damage" => 0,
                        "stacking_life_stealing" => 0,
                        "life_stealing" => 0,
                        "entrancing_chance" => 0,
                    ],
                    "spell_damage" => 0,
                    "weapon_damage" => 0,
                ],
                "defend" => [
                    "name" => "Sample",
                    "defence" => 50,
                    "ring_damage" => 50,
                    "artifact_damage" => 50,
                    "heal_for" => 50,
                    "res_chance" => 50.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 100,
                        "non_stacking_damage" => 100,
                        "stacking_life_stealing" => 10.0,
                        "life_stealing" => 10.0,
                        "entrancing_chance" => 10.0,
                    ],
                ],
                "voided_defend" => [
                    "name" => "Sample",
                    "defence" => 1430.0,
                    "ring_damage" => 0,
                    "artifact_damage" => 0,
                    "heal_for" => 0,
                    "res_chance" => 0.0,
                    "damage_deduction" => 0.0,
                    "affixes" => [
                        "cant_be_resisted" => true,
                        "stacking_damage" => 0,
                        "non_stacking_damage" => 0,
                        "stacking_life_stealing" => 0,
                        "life_stealing" => 0,
                        "entrancing_chance" => 0,
                    ],
                ],
            ],
            "character_data" => [
                "attack" => 0,
                "health" => 2839,
                "ac" => 10,
                "str_modded" => 2840.0,
                "dur_modded" => 2839.0,
                "dex_modded" => 2839.0,
                "chr_modded" => 2841.0,
                "int_modded" => 5669.0,
                "agi_modded" => 2838.0,
                "focus_modded" => 2838.0,
                "to_hit_base" => 2838,
                "voided_to_hit_base" => 2838,
                "artifact_annulment" => 0.0,
                "spell_evasion" => 0.0,
                "affix_damage_reduction" => 0.0,
                "healing_reduction" => 0.0,
                "devouring_light" => 1.0,
                "devouring_darkness" => 1.0,
                "skill_reduction" => 0.0,
                "resistance_reduction" => 0.0,
            ],
            "stat_affixes" => [
                "cant_be_resisted" => true,
                "all_stat_reduction" => null,
                "stat_reduction" => [],
                "skills" => [
                    [
                        "id" => 29,
                        "character_id" => 1,
                        "name" => "Accuracy",
                        "skill_bonus" => 0.0,
                        "skill_type" => "Training",
                        "xp" => 0,
                        "xp_max" => 652,
                        "current_xp" => 0,
                        "level" => 1,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 30,
                        "character_id" => 1,
                        "name" => "Dodge",
                        "skill_bonus" => 0.05,
                        "skill_type" => "Training",
                        "xp" => 0,
                        "xp_max" => 355,
                        "current_xp" => 0,
                        "level" => 1,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 31,
                        "character_id" => 1,
                        "name" => "Looting",
                        "skill_bonus" => 0.998,
                        "skill_type" => "Training",
                        "xp" => 0,
                        "xp_max" => 321,
                        "current_xp" => 0,
                        "level" => 999,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => 0.0,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 32,
                        "character_id" => 1,
                        "name" => "Weapon Crafting",
                        "skill_bonus" => 0.7025,
                        "skill_type" => "Crafting",
                        "xp" => 193,
                        "xp_max" => 204,
                        "current_xp" => 94.607843137255,
                        "level" => 82,
                        "max_level" => 400,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 33,
                        "character_id" => 1,
                        "name" => "Armour Crafting",
                        "skill_bonus" => 1.0,
                        "skill_type" => "Crafting",
                        "xp" => 0,
                        "xp_max" => 184,
                        "current_xp" => 0,
                        "level" => 400,
                        "max_level" => 400,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 34,
                        "character_id" => 1,
                        "name" => "Spell Crafting",
                        "skill_bonus" => 1.0,
                        "skill_type" => "Crafting",
                        "xp" => 26,
                        "xp_max" => 128,
                        "current_xp" => 20.3125,
                        "level" => 399,
                        "max_level" => 400,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 35,
                        "character_id" => 1,
                        "name" => "Ring Crafting",
                        "skill_bonus" => 0.65,
                        "skill_type" => "Crafting",
                        "xp" => 448,
                        "xp_max" => 619,
                        "current_xp" => 72.374798061389,
                        "level" => 1,
                        "max_level" => 400,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 36,
                        "character_id" => 1,
                        "name" => "Artifact Crafting",
                        "skill_bonus" => 0.93,
                        "skill_type" => "Crafting",
                        "xp" => 130,
                        "xp_max" => 156,
                        "current_xp" => 83.333333333333,
                        "level" => 173,
                        "max_level" => 400,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 37,
                        "character_id" => 1,
                        "name" => "Enchanting",
                        "skill_bonus" => 1.0,
                        "skill_type" => "Enchanting",
                        "xp" => 0,
                        "xp_max" => 187,
                        "current_xp" => 0,
                        "level" => 400,
                        "max_level" => 400,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 2368,
                        "character_id" => 1,
                        "name" => "Fighters Resilience",
                        "skill_bonus" => 0.0,
                        "skill_type" => "Effects Battle Timer",
                        "xp" => 154,
                        "xp_max" => 306,
                        "current_xp" => 50.326797385621,
                        "level" => 74,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => 0.1,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 2627,
                        "character_id" => 1,
                        "name" => "Quick Feet",
                        "skill_bonus" => 0.0,
                        "skill_type" => "Effects Movement Timer",
                        "xp" => 0,
                        "xp_max" => 108,
                        "current_xp" => 0,
                        "level" => 1,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 4335,
                        "character_id" => 1,
                        "name" => "Astral Magics",
                        "skill_bonus" => 0.0,
                        "skill_type" => "Training",
                        "xp" => 83,
                        "xp_max" => 226,
                        "current_xp" => 36.725663716814,
                        "level" => 232,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => 0.1,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 4709,
                        "character_id" => 1,
                        "name" => "Disenchanting",
                        "skill_bonus" => 1.0,
                        "skill_type" => "Disenchanting",
                        "xp" => 0,
                        "xp_max" => 135,
                        "current_xp" => 0,
                        "level" => 709,
                        "max_level" => 999,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 5083,
                        "character_id" => 1,
                        "name" => "Alchemy",
                        "skill_bonus" => 0.52,
                        "skill_type" => "Alchemy",
                        "xp" => 184,
                        "xp_max" => 201,
                        "current_xp" => 91.542288557214,
                        "level" => 15,
                        "max_level" => 200,
                        "can_train" => false,
                        "is_training" => false,
                        "xp_towards" => null,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 7179,
                        "character_id" => 1,
                        "name" => "Casting Accuracy",
                        "skill_bonus" => 0.996,
                        "skill_type" => "Training",
                        "xp" => 150,
                        "xp_max" => 336,
                        "current_xp" => 44.642857142857,
                        "level" => 997,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => true,
                        "xp_towards" => 0.5,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 7667,
                        "character_id" => 1,
                        "name" => "Criticality",
                        "skill_bonus" => 0.095,
                        "skill_type" => "Training",
                        "xp" => 165,
                        "xp_max" => 251,
                        "current_xp" => 65.737051792829,
                        "level" => 96,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => 0.1,
                        "is_locked" => false,
                    ],
                    [
                        "id" => 8155,
                        "character_id" => 1,
                        "name" => "Kingmanship",
                        "skill_bonus" => 0.998,
                        "skill_type" => "Effects the kingdom in some way",
                        "xp" => 0,
                        "xp_max" => 244,
                        "current_xp" => 0,
                        "level" => 999,
                        "max_level" => 999,
                        "can_train" => true,
                        "is_training" => false,
                        "xp_towards" => 0.0,
                        "is_locked" => false,
                    ],
                ],
            ]
        ];
    }
}
