#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn cleanup

git add -A

if ! git diff --cached --quiet; then
  echo "Changes detected. Committing formatted code..."
  git commit --no-verify -m "chore: auto-format code with Prettier"
else
  echo "No changes to commit."
fi
