name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      TIME_ZONE: America/Edmonton

    services:
      mysql-service:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: flare_test
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: pcov

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: |
          rm -rf vendor
          composer install --no-interaction --prefer-dist --no-progress
          yarn install

      # TODO: There is an issue with the way we use resizable box, commented for now to fix that later.
      # - name: Type check
      #   run: yarn type-check

      - name: Generate key
        run: php artisan key:generate

      - name: Link storage
        run: php artisan storage:link

      - name: Build frontend
        run: yarn build

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: flare_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
          TIME_ZONE: America/Edmonton
        run: php artisan migrate

      - name: Run Pest tests with coverage
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: flare_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
          TIME_ZONE: America/Edmonton
        run: |
          php -d memory_limit=-1 -d max_execution_time=0 ./vendor/bin/pest \
            --stop-on-failure \
            --coverage-html=./test-coverage

      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: laravel-test-coverage-${{ github.run_id }}-${{ github.sha }}
          if-no-files-found: warn
          retention-days: 14
          path: test-coverage/**